name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/opsara/investment-agent
            git pull origin main

            # Inject environment variables
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
            echo "REACT_APP_WS_URL=${{ secrets.REACT_APP_WS_URL }}" >> .env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
            echo "GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}" >> .env

            # Prune and clean up Docker
            docker system prune -af
            docker volume prune -f

            # Rebuild and restart Docker containers
            docker-compose down
            docker-compose up --build -d
          EOF
