name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/opsara/investment-agent
            git pull origin main

            # Inject frontend env
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > client/.env
            echo "REACT_APP_WS_URL=${{ secrets.REACT_APP_WS_URL }}" > client/.env

            # Inject backend env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > server/.env
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> server/.env
            echo "GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}" >> server/.env

            docker-compose down
            docker-compose up --build -d
          EOF
