name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu/opsara/investment-agent
            git stash
            git pull origin main

            # Create .env file with environment variables
            cat <<EOT > .env
REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
REACT_APP_WS_URL=${{ secrets.REACT_APP_WS_URL }}
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}
EOT

            # Prune and clean up Docker
            docker system prune -af
            docker volume prune -f

            # Build and deploy Docker containers with build arguments
            docker-compose build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} --build-arg REACT_APP_WS_URL=${{ secrets.REACT_APP_WS_URL }}
            docker-compose up -d
          EOF
